# Generated by Django 5.2.1 on 2025-11-09 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_order_photographypage_intro_subtitle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographypage',
            name='intro_subtitle',
        ),
        migrations.RemoveField(
            model_name='photographypage',
            name='intro_text',
        ),
        migrations.RemoveField(
            model_name='photographypage',
            name='intro_title',
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productpage',
            name='framed_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for the FRAMED A2 Print', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price for the RAW A2 Print', max_digits=7),
        ),
        migrations.DeleteModel(
            name='PhotographyPageGalleryImage',
        ),
    ]
