# Generated by Django 5.2.1 on 2025-11-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_photographypage_intro_subtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpage',
            name='framed_price',
        ),
        migrations.AddField(
            model_name='productpage',
            name='frame_addon_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ADD-ON price for the A2 Frame (e.g., 20.00). This will be added to the base price.', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price for the RAW A2 Print (e.g., 39.99)', max_digits=7),
        ),
    ]
