# Generated by Django 5.2.1 on 2025-11-13 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_productpage_framed_price_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintSizePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(help_text="Name der Größe, z.B. 'A2' oder 'A3'", max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Grundpreis für diesen Druck (ohne Rahmen)', max_digits=10)),
                ('frame_addon_price', models.DecimalField(decimal_places=2, help_text='Zusätzlicher Preis für einen Rahmen', max_digits=10)),
            ],
            options={
                'verbose_name': 'Druckgröße & Preis',
                'verbose_name_plural': 'Druckgrößen & Preise',
            },
        ),
        migrations.AlterModelOptions(
            name='productpage',
            options={'verbose_name': 'Produktseite'},
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='frame_addon_price',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='price',
        ),
        migrations.AlterField(
            model_name='productpage',
            name='description_text',
            field=models.TextField(blank=True, help_text='Einfache Textbeschreibung'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='orientation',
            field=models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical'), ('squared', 'Squared')], default='horizontal', help_text='Ausrichtung des Bildes', max_length=20),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='product_image',
            field=models.ForeignKey(help_text='Bild des Produkts', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='print_size',
            field=models.ForeignKey(help_text='Wähle die Größe, um den Preis automatisch festzulegen.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.printsizeprice', verbose_name='Druckgröße und Preis'),
        ),
    ]
