# Generated by Django 5.2.1 on 2025-11-14 16:46

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_printsizeprice_alter_productpage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpage',
            name='print_size',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='framed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='ProductSizeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_variants', to='home.productpage')),
                ('size_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.printsizeprice', verbose_name='Größe & Preis')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
