# Generated by Django 5.2.1 on 2025-11-14 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_productpage_print_size_orderitem_framed_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSizeVariant',
        ),
    ]
