# Generated by Django 5.2.1 on 2025-11-18 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_productsizevariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexshoppage',
            name='slider_product_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.productpage', verbose_name='Slide 1 Product Link'),
        ),
        migrations.AddField(
            model_name='indexshoppage',
            name='slider_product_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.productpage', verbose_name='Slide 2 Product Link'),
        ),
        migrations.AddField(
            model_name='indexshoppage',
            name='slider_product_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.productpage', verbose_name='Slide 3 Product Link'),
        ),
    ]
