# Generated by Django 5.2.1 on 2025-11-18 10:25

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_indexshoppage_slider_product_1_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexshoppage',
            name='slider_product_1',
        ),
        migrations.RemoveField(
            model_name='indexshoppage',
            name='slider_product_2',
        ),
        migrations.RemoveField(
            model_name='indexshoppage',
            name='slider_product_3',
        ),
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image_caption_title', models.CharField(blank=True, help_text='e.g., \'25" exposure\'', max_length=100)),
                ('image_caption_subtitle', models.CharField(blank=True, help_text="e.g., 'Namibia'", max_length=100)),
                ('slider_subtitle', models.CharField(blank=True, help_text="e.g., '#1 TRENDING ITEM'", max_length=255)),
                ('slider_title', wagtail.fields.RichTextField(help_text="The main title, e.g., 'CELESTIAL <br> RUNWAY'")),
                ('slider_description', models.TextField(blank=True, help_text='The main paragraph of text.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_products', to='home.indexshoppage')),
                ('product_to_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.productpage', verbose_name="Product to Link (for 'Buy Now')")),
                ('slider_image', models.ForeignKey(help_text='The main image for this slide.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
