# Generated by Django 5.2.1 on 2025-11-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_indexshoppage_slider_product_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('Austria', 'Austria'), ('Germany', 'Germany'), ('Switzerland', 'Switzerland'), ('Europe', 'Rest of Europe (EU)'), ('World', 'Rest of World')], default='Austria', max_length=100),
        ),
    ]
